version: 1
disable_existing_loggers: False
filters:
  request_id_filter:  # Changed name to be clear
    (): span_api_splitter.log_util.RequestIdFilter
formatters:
  standard:
    format: '%(asctime)s - %(name)s.%(module)s.%(funcName)s:%(lineno)d - %(levelname)s - %(request_id)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: CRITICAL
    filters: [request_id_filter]  # Match the name from filters section
loggers:
  audio_splitter_service:
    level: CRITICAL
    handlers: [console]
    propagate: false
root:
  level: CRITICAL
  handlers: [console]